export type Style={id:string;name:string;tagline:string;curve:string;fitness:string;defense:number;beginner:number;equipment:string[];benefits:string[];reasons:string[]};
export const styles:Style[]=[
{id:'boxing',name:'Boxing',tagline:'Footwork, hands, elite cardio.',curve:'Fast start, deep mastery',fitness:'High cardio, shoulders, core',defense:86,beginner:94,equipment:['Wraps','Gloves','Jump rope'],benefits:['Cardio engine','Confidence','Simple home drills'],reasons:['Strong cardio goals','Limited equipment','High confidence-building potential']},
{id:'muay-thai',name:'Muay Thai',tagline:'The art of eight limbs.',curve:'Moderate',fitness:'Full-body power and conditioning',defense:91,beginner:78,equipment:['Gloves','Shin guards'],benefits:['Power striking','Clinch strength','Mental toughness'],reasons:['Wants striking variety','Likes intense workouts','Self-defense focused']},
{id:'kickboxing',name:'Kickboxing',tagline:'High-energy striking fitness.',curve:'Beginner friendly',fitness:'Fat loss, legs, coordination',defense:82,beginner:88,equipment:['Gloves','Bag optional'],benefits:['Weight loss','Coordination','Stress relief'],reasons:['Fitness first','Home-workout friendly','Enjoys striking']},
{id:'bjj',name:'Brazilian Jiu-Jitsu',tagline:'Grappling, control, submissions.',curve:'Slow burn',fitness:'Functional strength and mobility',defense:93,beginner:80,equipment:['Gi or rash guard'],benefits:['Ground defense','Problem solving','Community'],reasons:['Self-defense interest','Lower striking preference','Builds calm under pressure']},
{id:'wrestling',name:'Wrestling',tagline:'Takedowns and relentless pressure.',curve:'Physically demanding',fitness:'Explosive strength and grit',defense:89,beginner:67,equipment:['Shoes optional'],benefits:['Athletic base','Balance','Work capacity'],reasons:['Competition interest','Strength goals','Likes grappling']},
{id:'judo',name:'Judo',tagline:'Throws, trips, safe falling.',curve:'Moderate',fitness:'Grip, hips, balance',defense:84,beginner:75,equipment:['Gi'],benefits:['Breakfalls','Throws','Discipline'],reasons:['Gym access','Self-defense','Wants tradition']},
{id:'karate',name:'Karate',tagline:'Precision, discipline, distance.',curve:'Accessible',fitness:'Mobility, speed, posture',defense:74,beginner:86,equipment:['Uniform optional'],benefits:['Focus','Flexibility','Distance control'],reasons:['Confidence building','Beginner structure','Technique focused']},
{id:'taekwondo',name:'Taekwondo',tagline:'Dynamic kicks and flexibility.',curve:'Accessible',fitness:'Leg strength and mobility',defense:70,beginner:84,equipment:['Uniform optional'],benefits:['Flexibility','Kicking skill','Agility'],reasons:['Mobility goals','Likes kicking','Motivated by ranks']},
{id:'mma',name:'MMA',tagline:'Blend striking, wrestling, grappling.',curve:'Complex',fitness:'Complete athletic development',defense:95,beginner:62,equipment:['Gloves','Shin guards','Rash guard'],benefits:['Well rounded','Competition ready','High variety'],reasons:['Competition interest','Gym access','Wants complete system']}
];
export const questions=[['age','Age range',['13-17','18-29','30-44','45+']],['fitness','Fitness level',['New beginner','Lightly active','Consistent','Athlete']],['weightLoss','Weight loss goal',['Low','Medium','High']],['muscle','Muscle gain goal',['Low','Medium','High']],['selfDefense','Self-defense interest',['Low','Medium','High']],['competition','Competition interest',['None','Curious','Definitely']],['equipment','Available equipment',['None','Jump rope','Gloves','Full kit']],['gym','Gym access',['No','Maybe','Yes']],['home','Home workout preference',['Prefer home','Hybrid','Prefer gym']],['days','Training days per week',['2','3','4','5+']],['preference','Striking vs Grappling',['Striking','Grappling','Both']],['confidence','Confidence level',['Nervous','Curious','Ready']],['injuries','Injury limitations',['None','Knees','Back','Shoulders']]] as const;
export const skillTrees={boxing:['Stance','Footwork','Jab','Cross','Hook','Defense','Combinations'],bjj:['Breakfall','Shrimp','Guard','Sweep','Armbar','Triangle'],muayThai:['Stance','Teep','Round kick','Knees','Clinch','Elbow'],mma:['Stance switch','Jab to shot','Sprawl','Ground control','Wall work','Transitions']};
export const workouts=[{day:'Monday',title:'Boxing fundamentals + core',blocks:['Warmup: 5 min jump rope','Skill: stance, guard, 100 jabs','Strength: planks and pushups','Conditioning: 6 x 30 sec shadowboxing','Recovery: shoulder mobility']},{day:'Wednesday',title:'Conditioning + shadowboxing',blocks:['Warmup: hip flow','Skill: jab-cross exits','Strength: squats and dead bugs','Conditioning: 12 min intervals','Recovery: nasal breathing']},{day:'Friday',title:'Technique drills',blocks:['Warmup: dynamic footwork','Skill: combo ladder','Strength: lunges','Conditioning: finisher EMOM','Recovery: calves and wrists']},{day:'Saturday',title:'Mobility and recovery',blocks:['Warmup: walk','Skill: balance drills','Strength: carries','Conditioning: zone 2 cardio','Recovery: full-body stretch']}];
export const achievements=['First Workout','7-Day Streak','100 Jabs Practiced','First Shadowboxing Session','Roadmap Rookie','Mobility Master','Coach Check-in','Gear Ready'];
export const gear=['Boxing gloves','Hand wraps','Jump rope','Mouthguard','Rash guard','Shin guards'];
export const rewards={workout:50,skill:25,streak:15,assessment:100};
